---
title: "Lab 06 - Functions and iterations"
author: "Quanyu Bao (s2568439)"
date: "`r Sys.Date()`"
output: html_document
---


### Packages and Data

```{r load-packages, message=FALSE}
library(tidyverse) 
library(ggplot2)
library(gridExtra)
```

```{r diamon_rename}
diamonds <- diamonds %>% rename(
    depth_pct = depth,
    length_mm = x,
    width_mm = y,
    depth_mm = z,
    table_pct = table
  )
```


## Exercise 1

```{r}
theme_set(theme_bw())

# Do some preliminary investigations & cleaning
diamonds <- diamonds %>%
  filter(depth_mm != 0)

diamonds %>%
  ggplot(mapping = aes(x = price, fill = cut)) + 
  geom_bar() 

plot1 <- diamonds %>%
  ggplot(mapping = aes(x = width_mm, y = depth_mm)) + 
  geom_point(alpha = 0.5,
             color = "orange",
             shape = 19) + 
  geom_smooth(method = "lm", 
              se = FALSE,
              color="darkorange") +
  labs(
        title = "Diamonds Depth against Width",
        x = "Width, in mm",
        y = "Depth, in mm"
          )

plot2 <- diamonds %>%
  ggplot(mapping = aes(x = length_mm, y = depth_mm)) + 
  geom_point(alpha = 0.5,
             color = "lightblue",
             shape = 19) + 
  geom_smooth(method = "lm", 
              se = FALSE,
              color = "blue") +
  labs(
        title = "Diamonds Depth against Length",
        x = "Length, in mm",
        y = "Depth, in mm"
          )

grid.arrange(plot1, plot2, ncol=2)
```


## Exercise 2

```{r}

diamonds <- diamonds %>%
  mutate(table_mm = table_pct * width_mm / 100)

# Overall table_mm arithmetic mean

diamonds %>%
  summarise(avg_table = mean(table_mm))

# table_mm arithmetic mean within each clarity category

diamonds %>% 
  group_by(clarity) %>%
  summarise(avg = mean(table_mm))
```

It seems that the better the quality of the diamond, the less table length they have as shown in the table above.

## Exercise 3

$$
\begin{equation}
\bar{x}_g=\sqrt[n]{\prod_{i=1}^n x_i}
\end{equation}
$$
$$
\begin{equation}
\ln{\bar{x}_g}=\ln{\sqrt[n]{\prod_{i=1}^n x_i}}
\end{equation}
$$
$$
\begin{equation}
\bar{x}_g=exp \left( {\ln{\sqrt[n]{\prod_{i=1}^n x_i}}} \right)
\end{equation}
$$
$$
\begin{equation}
\bar{x}_g= exp \left( \frac{1}{n}\ln{\prod_{i=1}^n x_i} \right)
\end{equation}
$$
$$
\begin{equation}
\bar{x}_g=exp \left( \frac{1}{n}\ln{(x_1 \cdot x_2 \cdot x_3 \cdot … \cdot x_i)} \right)
\end{equation}
$$
$$
\begin{equation}
\bar{x}_g=exp \left( \frac{1}{n} \left( \ln{x_1} + \ln{x_2} + \ln{x_3} + \dots + \ln{x_i} \right) \right)
\end{equation}
$$
$$
\begin{equation}
\bar{x}_g=exp \left( \frac{1}{n}\sum_{i=1}^n \ln{x_i} \right)
\end{equation}
$$
## Exercise 4

```{r}
# Write gmean() command
gmean <- function(x){
    n = length(x)
    exp(1/n * sum(log(x)))
}


```

## Exercise 5

```{r, error = TRUE}

test_data <- list(
  test1 = c(2.1, 3.8, 4.2),
  test2 = c(1, 10, 100, 1000),
  test3 = c(0, 1, 4),
  test4 = c(0.38,  0.94, -1.56),
  test5 = c(TRUE, TRUE),
  test6 = c("6", "7", "8")
)


# Create for loop to test gmean() on the above examples

for(i in test_data){
  print(i)
}

```


## Exercise 6

```{r}
# Copy gmean() from Ex4 and edit it to check the input





# Copy your code from Ex 5 to test your new command





```


## Exercise 7

```{r}
# Overall table_mm geometic mean?






# table_mm geometic mean within each clarity category






```

_Add your comment here_


## Exercise 8 (optional)

```{r}
# Create gmean2() that computes the geometric mean 
#   that uses the original definition






```


## Exercise 9 (optional)

```{r}
# Create a function that computes the harmonic mean







```
